title: David 的博客
subtitle: Welcome to David's Blog
description: 这里是程序员 David 的博客
keywords: 博客, 经验, 深度学习, DL, 机器学习, ML, 人工智能, AI, PyTorch
author: David
language: zh-CN
timezone: Asia/Shanghai
# 如果您的网站存放在子目录中，例如 http://example.com/blog，则请将您的 url 设为 http://example.com/blog 并把 root 设为 /blog/。
url: "https://david-deng.cn/my-blog/" # 网址, 必须以 http:// 或 https:// 开头
# url: "https://david-deng-01.gitee.io/my-blog/" # 网址, 必须以 http:// 或 https:// 开头
root: "/my-blog/" # 网站根目录 url's pathname
permalink: "/:year/:month/:day/:title/" # 文章的 永久链接 格式
permalink_defaults: null # 永久链接中各部分的默认值	
pretty_urls: # 改写 permalink 的值来美化 URL
  trailing_index: true # 是否在永久链接中保留尾部的 index.html，设置为 false 时去除
  trailing_html: true # 是否在永久链接中保留尾部的 .html, 设置为 false 时去除 (对尾部的 index.html无效)
source_dir: source # 资源文件夹，这个文件夹用来存放内容。
public_dir: public # 公共文件夹，这个文件夹用于存放生成的站点文件。
tag_dir: tags # 标签文件夹
archive_dir: archives # 归档文件夹
category_dir: categories # 分类文件夹
code_dir: downloads/code # Include code 文件夹，source_dir 下的子目录
i18n_dir: ":lang" # 国际化（i18n）文件夹
skip_render: null # 跳过指定文件的渲染。匹配到的文件将会被不做改动地复制到 public 目录中。您可使用 glob 表达式来匹配路径。
# new_post_name: ':title.md'
# Hexo 默认以标题做为文件名称，编辑 new_post_name 参数来改变默认的文件名称
new_post_name: ":year/:year-:month-:day/:title.md" # 新文章的文件名称
default_layout: post # 预设布局
auto_spacing: false # 在中文和英文之间加入空格
titlecase: false # 把标题转换为 title case
external_link: # 在新标签中打开链接
  enable: true # 在新标签中打开链接
  field: site # 对整个网站（site）生效或仅对文章（post）生效
  exclude: [] # 需要排除的域名。主域名和子域名如 www 需分别配置
filename_case: 0 # 把文件名称转换为 (1) 小写或 (2) 大写
render_drafts: false # 显示草稿
post_asset_folder: false # 是否使用相对资源文件夹
relative_link: false # 推荐不开启相对链接，开启容易出现资源无法找到的问题
future: true # 显示未来的文章
highlight: # 代码块的设置, 请参考 Highlight.js 进行设置
  enable: true
  auto_detect: true
  line_number: true
  line_threshold: 0
  tab_replace: '  '
  wrap: true
  hljs: false
prismjs: # 代码块的设置, 请参考 PrismJS 进行设置
  enable: false
  preprocess: false
  line_number: false
  tab_replace: ""
index_generator:
  path: ""
  per_page: 10
  order_by: "-date"
default_category: "uncategorized" # 默认分类
category_map: null # 分类别名
tag_map: null # 标签别名
meta_generator: true # Meta generator 标签。 值为 false 时 Hexo 不会在头部插入该标签
date_format: "YYYY-MM-DD" # 日期格式
time_format: "HH:mm:ss" # 时间格式
updated_option: mtime # 当 Front Matter 中没有指定 updated 时 updated 的取值
per_page: 10 # 每页显示的文章量 (0 = 关闭分页功能)
pagination_dir: page # 分页目录
include: [] # Hexo 默认会不包括 source/ 下的文件和文件夹（包括名称以下划线和 . 开头的文件和文件夹，Hexo 的 _posts 和 _data 等目录除外）。通过设置此字段将使 Hexo 处理他们并将它们复制到 source 目录下。
exclude: [] # Hexo 不包括 source/ 下的这些文件和目录
ignore: null # Hexo 会忽略整个 Hexo 项目下的这些文件夹或文件
theme: butterfly # 当前主题名称。值为false时禁用主题
# theme_config: "_config.fluid.yml" # 主题的配置文件。在这里放置的配置会覆盖主题目录下的 _config.yml 中的配置

deploy: # 部署部分的设置
  type: git
  repo: "git@gitee.com:david-deng-01/my-blog.git"
  branch: master

nofollow:
  enable: true
  field: site
  exclude:

# 站点地图
sitemap:
  path: sitemap.xml
  rel: false
  tags: true
  categories: true

marked:
  smartypants: false
  descriptionLists: false

